import { describe, expect, it } from 'vitest';
import {
  extractPrestigeError,
  expandCrewInventory,
  optimizeConcurrentPrestigePlan,
  parsePrestigePaths,
  parseCrewInventory,
  preprocessPrestigeText,
  rankPrestigeOptionsForInventory,
  resolveCrewInventory,
  prestigeHtmlToText
} from '../src/features/prestige/prestigePath.js';

describe('prestige path parsing and optimization', () => {
  it('builds a fusion tree from equations', () => {
    const result = parsePrestigePaths(`
      Zombie + Ribi -&gt; Orc<br>
      Orc + Abbie -&gt; Turkey Hero<br>
      Turkey Hero + Nova 5 -&gt; Paralympic God
    `, 'Paralympic God');

    expect(result.optimal.root.name).toBe('Paralympic God');
    expect(result.optimal.root.children[0].name).toBe('Turkey Hero');
    expect(result.optimal.root.children[0].children[0].name).toBe('Orc');
    expect(result.optimal.metrics.operations).toBe(3);
  });

  it('chooses fewer missing crew before a shorter path', () => {
    const result = parsePrestigePaths(`
      Solution 1<br>
      Target<br>
      +-- <span style="color: red">Missing A</span><br>
      +-- Owned B<br><br>
      Solution 2<br>
      Target<br>
      +-- Owned C<br>
      +-- Owned D
    `, 'Target');

    expect(result.options).toHaveLength(2);
    expect(result.optimal.metrics.missing).toBe(0);
    expect(result.optimal.root.children[0].name).toBe('Owned C');
  });

  it('extracts embedded upstream errors without preserving HTML', () => {
    const html = '<p>Error: Could not fetch crew data. Please check the username.</p>';
    expect(extractPrestigeError(html)).toBe('Could not fetch crew data. Please check the username.');
    expect(prestigeHtmlToText(html)).toBe('Error: Could not fetch crew data. Please check the username.');
  });

  it('never treats upstream metadata as an optimal crew tree', () => {
    const result = parsePrestigePaths(`
      Prestige data from: 2026-07-01<br>
      Recipe rotation: current<br>
      Generated by Blackhand
    `, 'Paralympic God');

    expect(result.options).toHaveLength(0);
    expect(result.optimal).toBeNull();
    expect(result.text).toContain('Prestige data from: 2026-07-01');
  });

  it('keeps the prestige timestamp and preprocesses output from Path 1 onward', () => {
    const source = `
      Prestige data from: 2026-08-31 23:31:33
      Generated by Blackhand
      Introductory text that is not part of the paths
      Path 1: Zombie + Ribi -> Orc
      Orc + Abbie -> Paralympic God
      Path 2:
      Zombie + Abbie -> Paralympic God
    `;

    const text = preprocessPrestigeText(source);
    const result = parsePrestigePaths(source, 'Paralympic God');

    expect(text).toContain('Prestige data from: 2026-08-31 23:31:33');
    expect(text).not.toContain('Generated by Blackhand');
    expect(text).not.toContain('Introductory text');
    expect(text).toContain('Path 1: Zombie + Ribi -> Orc');
    expect(result.options).toHaveLength(2);
    expect(result.optimal.root.name).toBe('Paralympic God');
  });

  it('builds one tree from an upstream arrow-separated path chain', () => {
    const result = parsePrestigePaths(`
      <p>Prestige data from: 2026-08-31 23:31:33</p>
      <p>5419 Paths found to create Paralympic God:</p>
      <div class="path-line">Path 1: Mama (1) + Qtarian Healer (1) = Sherry → Sherry + First Mate (40) = Admiral Yi → Admiral Yi + Miss Jane (40) = Paralympic God</div>
      <div class="path-line">Path 2: Zombie (1) + Ribi (1) = Orc → Orc + Abbie (1) = Turkey Hero → Turkey Hero + Nova 5 (40) = Paralympic God</div>
    `, 'Paralympic God');

    expect(result.options).toHaveLength(2);
    expect(result.optimal.root.name).toBe('Paralympic God');
    expect(result.optimal.metrics.operations).toBe(3);
    expect(result.optimal.root.children[0].name).toBe('Admiral Yi');
    expect(result.optimal.root.children[0].children[0].name).toBe('Sherry');
    expect(result.optimal.root.children[0].children[0].children.map(({ name }) => name)).toEqual([
      'Mama (1)',
      'Qtarian Healer (1)'
    ]);
  });

  it('parses manual quantities and ranks paths by maximum craftable copies', () => {
    const parsed = parsePrestigePaths(`
      Path 1: Zombie + Ribi = Orc → Orc + Abbie = Target
      Path 2: Mama + Mama = Eric → Eric + Abbie = Target
    `, 'Target');
    const inventory = parseCrewInventory('4xMama\n2xAbbie\nZombie\nRibi');
    const ranked = rankPrestigeOptionsForInventory(parsed.options, '4xMama\n2xAbbie\nZombie\nRibi');

    expect(inventory.get('mama').count).toBe(4);
    expect(expandCrewInventory('2xMama, Abbie')).toBe('Mama, Mama, Abbie');
    expect(ranked[0].root.children[0].name).toBe('Eric');
    expect(ranked[0].craftableCopies).toBe(2);
    expect(ranked[0].metrics.missing).toBe(0);
    expect(ranked[1].craftableCopies).toBe(1);
  });

  it('combines different paths against one shared inventory to maximize targets', () => {
    const parsed = parsePrestigePaths(`
      Path 1: Alpha + Beta = Target
      Path 2: Gamma + Delta = Target
      Path 3: Alpha + Gamma = Target
    `, 'Target');
    const plan = optimizeConcurrentPrestigePlan(
      parsed.options,
      'Alpha, Beta, Gamma, Delta',
      'Target'
    );

    expect(plan.maximumCopies).toBe(2);
    expect(plan.routes).toHaveLength(2);
    expect(plan.routes.reduce((sum, route) => sum + route.plannedCopies, 0)).toBe(2);
  });

  it('solves concurrent targets from a recipe catalog even when complete paths are capped', () => {
    const recipes = [
      { left: 'Alpha', right: 'Beta', output: 'Target' },
      { left: 'Gamma', right: 'Delta', output: 'Target' }
    ];
    const plan = optimizeConcurrentPrestigePlan(
      [],
      'Alpha, Beta, Gamma, Delta',
      'Target',
      recipes
    );

    expect(plan.maximumCopies).toBe(2);
    expect(plan.routes).toHaveLength(2);
    expect(plan.exact).toBe(true);
  });

  it('resolves common manual aliases and close misspellings against the crew catalog', () => {
    const resolved = resolveCrewInventory(
      '3xStudent, Visiri Assasin, Keria, Mr Clay, Olympic Pagan Burger, Sportman Ronny, 5xPilot',
      ['Good student', 'Visiri Assassin', 'Keira', 'Mr Cray', 'Olympian Pagan Burger', 'Sportsman Ronny', 'Civilian Pilot']
    );

    expect(resolved.text).toContain('3xGood student');
    expect(resolved.text).toContain('1xVisiri Assassin');
    expect(resolved.text).toContain('1xOlympian Pagan Burger');
    expect(resolved.text).toContain('5xCivilian Pilot');
    expect(resolved.unmatched).toEqual([]);
  });
});
